### ISSUE TITLE
Help creating a private network

### ISSUE THREAD

**Issue by hynese** [iotaledger/iri#475]
Greetings,

I have four IRI nodes running on my local machine (docker).

They are at: 172.19.0.101, 172.19.0.102, 172.19.0.103 and 172.19.0.104  

All have the following ports exposed: 14265, 14600, 15600, 16600, 18600

But my network seems frozen! How do I get it to do something?!

I tried connecting IOTA wallet to udp://localhost:16600 to no avail ;(

Here's my `Docker` file:

```
FROM maven:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN mkdir -p /iri/data
RUN mkdir -p /iri/conf

RUN git clone https://github.com/iotaledger/iri
WORKDIR /usr/src/app/iri

RUN mvn clean compile
RUN mvn package

#version number could change
RUN cp ./target/iri-* ./target/out.jar

CMD ["java","-jar","./target/out.jar","-p","14265","-n","udp://172.19.0.101:14600 udp://172.19.0.102:14602 udp://172.19.0.103:14603 udp://172.19.0.104:14604"]
```

And here's my `docker-compose.yml`:

```
version: '2.1'



networks:
  net_private:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24
         gateway: 172.19.0.1   #yes, no hypen!

services:
iota-iri-1:
    container_name: iota-iri-1
    build: ./services/iota-iri
    volumes:
      - './services/iota-iri/mnt/1/data:/iri/data'
      - './services/iota-iri/mnt/1/conf:/iri/conf'
      - './services/iota-iri/iri:/usr/scr/app/iri'
      #- './services/iota-iri/iota.ini:/iri/iota.ini'
      #- './services/iota:/usr/src/app'
      #- '/usr/src/app/node_modules'
    ports:
      - '${PORT}:${PORT}' # expose ports - HOST:CONTAINER
      - '${API_PORT}:${API_PORT}'
      - '${IRI_PORT}:${IRI_PORT}'
      - '${UDP_PORT}:${UDP_PORT}/udp'
      - '${TCP_PORT}:${TCP_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - UDP_PORT=${UDP_PORT}
      - TCP_PORT=${TCP_PORT}
    networks:
      net_private:
        ipv4_address: 172.19.0.101
    # depends_on:
    #   iota-nelson:
    #     condition: service_healthy
    healthcheck:
      test: exit 0






  iota-iri-2:
    container_name: iota-iri-2
    build: ./services/iota-iri
    volumes:
      - './services/iota-iri/mnt/2/data:/iri/data'
      - './services/iota-iri/mnt/2/conf:/iri/conf'
      - './services/iota-iri/iri:/usr/scr/app/iri'
      #- './services/iota-iri/iota.ini:/iri/iota.ini'
      #- './services/iota:/usr/src/app'
      #- '/usr/src/app/node_modules'
    ports:
      - '${PORT2}:${PORT}' # expose ports - HOST:CONTAINER
      - '${API_PORT2}:${API_PORT}'
      - '${IRI_PORT2}:${IRI_PORT}'
      - '${UDP_PORT2}:${UDP_PORT}/udp'
      - '${TCP_PORT2}:${TCP_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - UDP_PORT=${UDP_PORT}
      - TCP_PORT=${TCP_PORT}
    networks:
      net_private:
        ipv4_address: 172.19.0.102
    # depends_on:
    #   iota-nelson:
    #     condition: service_healthy
    healthcheck:
      test: exit 0






  iota-iri-3:
    container_name: iota-iri-3
    build: ./services/iota-iri
    volumes:
      - './services/iota-iri/mnt/3/data:/iri/data'
      - './services/iota-iri/mnt/3/conf:/iri/conf'
      - './services/iota-iri/iri:/usr/scr/app/iri'
      #- './services/iota-iri/iota.ini:/iri/iota.ini'
      #- './services/iota:/usr/src/app'
      #- '/usr/src/app/node_modules'
    ports:
      - '${PORT3}:${PORT}' # expose ports - HOST:CONTAINER
      - '${API_PORT3}:${API_PORT}'
      - '${IRI_PORT3}:${IRI_PORT}'
      - '${UDP_PORT3}:${UDP_PORT}/udp'
      - '${TCP_PORT3}:${TCP_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - UDP_PORT=${UDP_PORT}
      - TCP_PORT=${TCP_PORT}
    networks:
      net_private:
        ipv4_address: 172.19.0.103
    # depends_on:
    #   iota-nelson:
    #     condition: service_healthy
    healthcheck:
      test: exit 0






  iota-iri-4:
    container_name: iota-iri-4
    build: ./services/iota-iri
    volumes:
      - './services/iota-iri/mnt/4/data:/iri/data'
      - './services/iota-iri/mnt/4/conf:/iri/conf'
      - './services/iota-iri/iri:/usr/scr/app/iri'
      #- './services/iota-iri/iota.ini:/iri/iota.ini'
      #- './services/iota:/usr/src/app'
      #- '/usr/src/app/node_modules'
    ports:
      - '${PORT4}:${PORT}'   # expose ports - HOST:CONTAINER
      - '${API_PORT4}:${API_PORT}'
      - '${IRI_PORT4}:${IRI_PORT}'
      - '${UDP_PORT4}:${UDP_PORT}/udp'
      - '${TCP_PORT4}:${TCP_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - UDP_PORT=${UDP_PORT}
      - TCP_PORT=${TCP_PORT}
    networks:
      net_private:
        ipv4_address: 172.19.0.104
    # depends_on:
    #   iota-nelson:
    #     condition: service_healthy
    healthcheck:
      test: exit 0
```

`.env` file:

```
NODE_ENV=development

PORT=16600
API_PORT=18600
IRI_PORT=14265
UDP_PORT=14600
TCP_PORT=15600

PORT2=16602
API_PORT2=18602
IRI_PORT2=14267
UDP_PORT2=14602
TCP_PORT2=15602

PORT3=16603
API_PORT3=18603
IRI_PORT3=14268
UDP_PORT3=14603
TCP_PORT3=15603

PORT4=16604
API_PORT4=18604
IRI_PORT4=14269
UDP_PORT4=14604
TCP_PORT4=15604
```

I wonder can anyone help me move beyond this point?

I'm trying to put a web front-end on top of a private IOTA network.
