### ISSUE TITLE
I can't to launch the IRI docker

### ISSUE THREAD

**Issue by 1scrooge** [iotaledger/iri#849]
I am trying launch docker. But I have a problem.
I have used docker-compose:
```
version: '2'

services:
  iota-node:
    container_name: iota-mainnet-node
    restart: always
    image: iotaledger/iri
#    mem_limit: 4G
    volumes:
      - ./mainnet:/iri/mainnetdb
      - ./iota.ini:/iri/iota.ini
    ports:
      - "14777:14777/udp"
      - "15777:15777/tcp"
      - "14265:14265"
```
my error:
```
$ docker-compose logs -f
Attaching to iota-mainnet-node
iota-mainnet-node | Logging - property 'logging-level' set to: [INFO]
iota-mainnet-node | 07/02 15:44:58.838 [main] ERROR com.iota.iri.IRI$IRILauncher - Invalid arguments list. Provide at least the PORT in iota.ini or with -p option
iota-mainnet-node | 07/02 15:44:58.876 [main] INFO  com.iota.iri.IRI$IRILauncher - Usage: java -jar IRI-1.5.0.jar [{-n,--neighbors} '<list of neighbors>'] [{-p,--port} 14265] [{-c,--config} 'config-file-name'] [{-u,--udp-receiver-port} 14600] [{-t,--tcp-receiver-port} 15600] [{-d,--debug} false] [{--testnet} false][{--remote} false][{--remote-auth} string][{--remote-limit-api} string]
```
iota.ini
```
[IRI]
CONFIG = iota.ini
PORT = 14265
UDP_RECEIVER_PORT = 14777
TCP_RECEIVER_PORT = 15777
#TESTNET = true
IXI_DIR = ixi
DB_PATH = mainnetdb
DB_LOG_PATH = mainnet.log
NEIGHBORS = tcp://18.196.13.104:15600 tcp://h2790715.stratoserver.net:14600 tcp://13.82.186.212:15600 tcp://40.118.124.179:15777 tcp://node01.iri.host:14600
REMOTE_LIMIT_API = "addNeighbors, removeNeighbors"
#HEADLESS = true
DEBUG = false
```
